apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8-kafka-external-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: k8-kafka-secret-store
    kind: SecretStore
  target:
    name: final-secret
    creationPolicy: Owner
  # data:
  # - secretKey: secret-key-to-be-managed
  #   remoteRef:
  #     key: provider-key
  #     version: provider-key-version
  #     property: provider-key-property
  dataFrom:
  - extract:
      key: kafka-kubernetes-secrets


