apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: k8-kafka-secret-store
spec:
  provider: 
    aws:
      service: SecretsManager
      region: eu-north-1 
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: access_key
          secretAccessKeySecretRef: 
            name: aws-credentials
            key: secret_access_key